services:
  nginx:
    container_name: tr-nginx
    build:
      context: ./devops/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tests/:/usr/share/nginx/html
    # depends_on:
    #   - game-service
    #   - tournament-service
    networks:
      - transcendence-network

  # game-service:
  #   container_name: game-service
  #   build:
  #     context: ./backend/services/game-service
  #   ports:
  #     - "3003:3003"
  #   volumes:
  #     - ./backend/services/game-service:/app
  #     - ./databases:/app/data
  #   networks:
  #     - transcendence-network
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_TYPE=sqlite
  #     - DATABASE_PATH=/app/data/game.db

  # tournament-service:
  #   container_name: tournament-service
  #   build:
  #     context: ./backend/services/tournament-service
  #   ports:
  #     - "3004:3004"
  #   volumes:
  #     - ./backend/services/tournament-service:/app
  #     - ./databases:/app/data
  #   networks:
  #     - transcendence-network
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_TYPE=sqlite
  #     - DATABASE_PATH=/app/data/tournament.db

networks:
  transcendence-network:
    driver: bridge