
name: tr
services:
  nginx:
    container_name: nginx
    build:
      context: ./devops/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - game-service
    #   - tournament-service
    networks:
      - transcendence-network

  game-service:
    container_name: game-service
    build:
      context: ./backend/services/game-service
    volumes:
      - ./backend/services/game-service/src:/app/src
    networks:
      - transcendence-network


networks:
  transcendence-network:
    driver: bridge
